server {
    listen 80;
    server_name localhost;

    # Указываем корневую директорию для статики
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Правило для обработки всех запросов
    location / {
        try_files $uri $uri/ /index.html;
    }
}
